Models/ApplicationDBContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace AppMVC.Models
{
    public class ApplicationDBContext : DbContext
    {
        public ApplicationDBContext(DbContextOptions<ApplicationDBContext> options):base(options){}
         protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
           
        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
        }
    }
}

Models/ErrorViewModel.cs
namespace AppMVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/PlanetModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AppMVC.Models
{
    public class PlanetModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string VnName { get; set; }
        public string Content { get; set; }
    }
}

Models/ProductModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AppMVC.Models
{
    public class ProductModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
    }
}

Areas/Database/Controllers/DbManageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AppMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AppMVC.Areas.Database.Controllers
{
    [Area("Database")]
    [Route("/database-manage/[action]")]
    public class DbManageController : Controller
    {
        private readonly ApplicationDBContext _dbContext;
        public DbManageController(ApplicationDBContext dBContext){
            _dbContext = dBContext;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult DeleteDB()
        {
            return View();
        }
        [TempData]
        public string StatusMessage { get; set; }
        [HttpPost]
        public async Task<IActionResult> DeleteDBAsync(){
           var success= await _dbContext.Database.EnsureDeletedAsync();
           StatusMessage = success ? "Successfully" : "Failed";
           return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public async Task<IActionResult> Migrate(){
           await _dbContext.Database.MigrateAsync();
           StatusMessage = "Successfully";
           return RedirectToAction(nameof(Index));
        }
    }
}

Areas/ProductManage/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AppMVC.Services;
using Microsoft.AspNetCore.Mvc;

namespace AppMVC.Controllers
{
    [Area("ProductManage")]
    public class ProductController : Controller
    {
        private readonly ProductService _productService;
        private readonly ILogger<ProductController> _logger;
        public ProductController(ProductService productService, ILogger<ProductController> logger){
            _productService = productService;
            _logger = logger;
        }
        public IActionResult Index()
        {
            var products = _productService.OrderBy(p => p.Name).ToList();
            return View(products);
        }
    }
}

Controllers/FirstController.cs
using System.IO.Compression;
using System.Net.Mime;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AppMVC.Services;

namespace AppMVC.Controllers
{
    public class FirstController : Controller
    {
        private readonly ILogger<FirstController> _logger;
        private readonly IWebHostEnvironment _environment;
        private readonly ProductService _productService;
        public FirstController(ILogger<FirstController> logger , IWebHostEnvironment environment,ProductService productService){
            _logger = logger;
            _environment = environment;
            _productService = productService;
        }
        public string Index(){
            _logger.LogInformation("Index Action");
            return "Toi la Index cua First";
        }
        public void Nothing(){
            _logger.LogInformation("Nothing action");
            Response.Headers.Add("hi","xin chao cac ban");
        }
        public IActionResult Readme(){
            var content = @"
            xin chao cac ban,
            Thanh Dat";
            return Content(content,"text/plain");
        }
        public IActionResult Bird()
        {
            string filePath = Path.Combine(_environment.ContentRootPath,"Files","Bird.jpeg");
            var bytes = System.IO.File.ReadAllBytes(filePath);
            return File(bytes, "image/jpeg");
        }
        public IActionResult IphonePrice()
        {
            return Json(
                new{
                    productName= "Iphone X",
                    Price = 1000
                }
            );
        }
        public IActionResult HelloView(string username)
        {
            if(string.IsNullOrEmpty(username))
            {
                username = "Khach";
            }
            return View("xinchao2", username);
        }
        [AcceptVerbs("POST","GET")]
        public IActionResult ViewProduct(int? id){
            var product = _productService.FirstOrDefault( p=> p.Id == id);
            if(product == null){
                TempData["Thongbao"]= "NotFound";
                return Redirect(Url.Action("Index","Home"));
            }
            // this.ViewData["product"] = product;
            ViewBag.product = product;
            return View("ViewProduct3");
        }
    }
    
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AppMVC.Models;

namespace AppMVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }
    public string HiHome() => "Xin chao cac ban";

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/PlanetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AppMVC.Services;
using Microsoft.AspNetCore.Mvc;

namespace AppMVC.Controllers
{
    public class PlanetController : Controller
    {
        private readonly PlanetService _planetService;
        private readonly ILogger<PlanetController> _logger;
        public PlanetController(PlanetService planetService, ILogger<PlanetController> logger){
            _planetService = planetService;
            _logger = logger;
        }
        [Route("danh-sach-cac-hanh-tinh.html")]
        public IActionResult Index()
        {
            return View();
        }
        [BindProperty(SupportsGet = true, Name = "action")]
        public string Name { get; set; }
        public IActionResult Mercury()
        {
            var planet = _planetService.FirstOrDefault(p => p.Name == Name);
            return View("Detail",planet);
        }
        [Route("sao/[action]")]
         public IActionResult Venus()
        {
            var planet = _planetService.FirstOrDefault(p => p.Name == Name);
            return View("Detail",planet);
        }
        [Route("hanhtinh/{id:int}")]
        public IActionResult PlanetInfo(int id){
            var planet = _planetService.FirstOrDefault(p => p.Id == id);
            return View("Detail",planet);
        }
    }
}

Pages/Razor.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace AppMVC.Pages
{
    public class Razor : PageModel
    {
        private readonly ILogger<Razor> _logger;

        public Razor(ILogger<Razor> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Areas/Database/Views/DbManage/DeleteDB.cshtml
@{
    ViewData["Title"] = "Delete DB";
}
<h1>@ViewData["Title"]</h1>
<p class="alert alert-danger">
    Are u sure ?
</p>
<form method="post">
    <button type="submit" class="btn btn-danger">Delete</button>
    <hr>
    <a asp-action="Index">Manage DB</a>
</form>

Areas/Database/Views/DbManage/Index.cshtml
@using Microsoft.EntityFrameworkCore
@using System.Data


@inject ApplicationDBContext dbContext
@{
    ViewData["Title"] = "DB INFOR";
    var connect = dbContext.Database.GetDbConnection();
    var dbname = connect.Database;
    var can_connect = dbContext.Database.CanConnect();
}
<partial name ="_AlertMessage"/>
<h1>Database Management</h1>
<p>-Database: @dbname</p>
<p>-Source: @connect.DataSource</p>
<p>-State: @connect.State</p>
<hr>
<h2>Migrations</h2>
@foreach (var migrations in dbContext.Database.GetAppliedMigrations())
{
    <p>@migrations</p>
}
@foreach (var migrations in dbContext.Database.GetPendingMigrations())
{
    <p>@migrations (pending)</p>
}
@if(!can_connect){
    <p class="alert alert-danger">Cannot connect to DB</p>
}
@if(dbContext.Database.GetPendingMigrations().Any()){
    <form method="post">
        <button class="btn btn-success" asp-action="Migrate">Create DB(Update Migration)</button>
    </form>
}
@if (can_connect)
{
    <h2>Tables</h2>
    await dbContext.Database.OpenConnectionAsync();
    var table = dbContext.Database.GetDbConnection().GetSchema("Tables");
    <ul>
    @foreach (System.Data.DataRow item in table.Rows)
    {
        <li>@item["TABLE_NAME"]</li>
        
    }
    </ul>
    <a class="btn btn-danger" asp-action="DeleteDB">Delete DB: @dbname</a>
}

Areas/ProductManage/Views/Product/Index.cshtml
@using AppMVC.Models
@model List<ProductModel>
<h1>List Product</h1>
<ul>
    @foreach(var product in Model)
    {
        <li>
            @product.Name
        </li>
    }
</ul>

Pages/Razor.cshtml
@page "/aboutrazor.html"
@model AppMVC.Pages.Razor
@{
    ViewData["Title"] = "Razor";
    Layout = "_Layout";
}

<h1>@ViewData["Title"]</h1>

<div>
    
</div>

Views/First/ViewProduct.cshtml
@model AppMVC.Models.ProductModel

<div class="card bg-danger text-white">
    <h1 class="card-header">@Model.Name</h1>
    <div class="card-body">
        <p class="card-text">
            Gia: @Model.Price;
        </p>
    </div>
</div>

Views/First/ViewProduct2.cshtml
@model AppMVC.Models.ProductModel
@{
    var product = ViewData["product"] as ProductModel;
}
<div class="card bg-primary text-white">
    <h1 class="card-header">@product.Name</h1>
    <div class="card-body">
        <p class="card-text">
            Gia: @product.Price;
        </p>
    </div>
</div>

Views/First/ViewProduct3.cshtml
@model AppMVC.Models.ProductModel
@{
    var product = ViewBag.product as ProductModel;
}
<div class="card bg-warning text-white">
    <h1 class="card-header">@product.Name</h1>
    <div class="card-body">
        <p class="card-text">
            Gia: @product.Price;
        </p>
    </div>
</div>

Views/First/xinchao2.cshtml
@model string
@{
   
    Layout = "_Layout";
}

<h1>Hello @Model</h1>

<div>
    @this.Path
</div>

Views/Home/Index.cshtml
@{
  
}
<partial name="_AlertMessage"/>
<div class="text-center">
    <h1 class="display-4">Xin chào</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Planet/Detail.cshtml
@model AppMVC.Models.PlanetModel

<h1>@Model.Name</h1>

<div class="card w-50">
    <img class="card-img-top" src="~/planet/@(Model.Name).jpg" alt=""/>
    <div class="card-body">
        <h5>@Model.VnName</h5>
     <div class="card-text">
        @Model.Content
    </div>
    <a class="card-link" asp-action="Index">Other Planets</a>
    </div>
  
</div>

Views/Planet/Index.cshtml
@inject AppMVC.Services.PlanetService planetService
<h1>Cac hanh tinh trong he mat troi</h1>
<div class="list-group">
    @foreach (var planet in planetService)
{
    <a class="list-group-item list-group-item-action" asp-action="@planet.Name">
        @planet.VnName - @planet.Name
    </a>
}
</div>

Views/Product/Index.cshtml
@model List<ProductModel>

<h1>List Product</h1>
<ul>
    @foreach(var product in Model)
    {
        <li>
            @product.Name
        </li>
    }
</ul>

Views/Shared/_AlertMessage.cshtml
@{
    var message = TempData["StatusMessage"] as string;
}
@if(!string.IsNullOrEmpty(message)){
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
  @message
  <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AppMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Planet" asp-action="Index">Planet</a>
                        </li>
                    </ul>
                    <partial name="_MenuManagePartial"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AppMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_MenuManagePartial.cshtml
<div class="dropdown show">
  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="managedropdownmenu" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Manage
  </a>

  <div class="dropdown-menu" aria-labelledby="managedropdownmenu">
   <a class="dropdown-item" asp-action="Index" asp-controller="DbManage" asp-area="Database">
    Database
   </a>
  </div>
</div>